FROM node:20-alpine

# Instalar dependencias para WhatsApp Web.js
RUN apk add --no-cache chromium nss freetype harfbuzz ca-certificates ttf-freefont

# Decirle a Puppeteer que use Chromium del sistema
ENV PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser

WORKDIR /app

# Copiar archivos de la app
COPY package.json .
RUN npm install

COPY server.js .

EXPOSE 8080

CMD ["node", "server.js"]